routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('admin', 'AdminController');
Route::resource('atur_akun', 'AccountSettingController');
Route::resource('akun', 'AccountController');
Route::resource('bahan_baku', 'IngredientController');
Route::resource('bahan_baku_menu', 'MenuIngredientController');
Route::resource('biaya_lain', 'OtherTransactionController');
Route::resource('cabang', 'BranchController');
Route::resource('jenis_akun', 'AccountTypeController');
Route::resource('jenis_pembayaran', 'PaymentTypeController');
Route::resource('jurnal', 'JournalController');
Route::resource('kasir', 'CashierController');
Route::resource('kategori', 'CategoryController');
Route::resource('member', 'MemberController');
Route::resource('menu', 'MenuController');
Route::resource('owner', 'OwnerController');
Route::resource('satuan', 'UnitController');
Route::resource('transfer', 'TransferController');
Route::resource('pembelian', 'RestockController');
Route::resource('penjualan', 'TransactionController');
Route::resource('brand', 'StoreController');
Route::resource('jenis_penjualan', 'TransactionTypeController');
Route::resource('konversi_poin', 'SettingPointController');
Route::resource('riwayat_poin', 'HistoryPointController');

Route::get('/get_branch/{store_id}', 'BranchController@get_branch');
Route::get('/get_unit/{branch_id}', 'UnitController@get_unit');
Route::get('/get_category/{branch_id}', 'CategoryController@get_category');
Route::get('/get_ingredient/{branch_id}', 'IngredientController@get_ingredient');
Route::get('/get_account_type/{branch_id}', 'AccountTypeController@get_account_type');
Route::get('/get_account/{branch_id}', 'AccountController@get_account');
Route::get('/get_payment_type/{branch_id}', 'PaymentTypeController@get_payment_type');

Route::get('/laporan/neraca', 'ReportController@neraca_pre')->name('neraca_pre');
Route::get('/laporan/laba_rugi', 'ReportController@laba_rugi_pre')->name('laba_rugi_pre');
Route::get('/laporan/arus_kas', 'ReportController@arus_kas_pre')->name('arus_kas_pre');
Route::get('/laporan/neraca/{store_id}/{branch_id}', 'ReportController@neraca')->name('neraca');
Route::get('/laporan/laba_rugi/{store_id}/{branch_id}', 'ReportController@laba_rugi')->name('laba_rugi');
Route::get('/laporan/arus_kas/{store_id}/{branch_id}', 'ReportController@arus_kas')->name('arus_kas');

Route::get('/invoice_download/penjualan/{transaction_id}', 'PDFController@invoice_transaction');
Route::get('/invoice_download/pembelian/{restock_id}', 'PDFController@invoice_restock');
Route::get('/invoice_download/transfer/{transfer_id}', 'PDFController@invoice_transfer');
Route::get('/invoice_download/biaya_lain/{other_transaction_id}', 'PDFController@invoice_other_transaction');

app/Branch.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use DB;

class Branch extends Model
{
    protected $table = "branch";
    protected $primaryKey = "branch_id";
    public $timestamps = false;

    public function SelectBranch($store_id = 0) {
    	if($store_id == 0) {
	    	return $branches = DB::table('branch')
	    		->join('store', 'store.store_id', '=', 'branch.store_id')
	    		->where('branch_delete', '=', 0)
                ->where('store_delete', '=', 0)
	    		->get();
    	} else {
	    	return $branches = DB::table('branch')
	    		->join('store', 'store.store_id', '=', 'branch.store_id')
	    		->where('store.store_id', '=', $store_id)
	    		->where('branch_delete', '=', 0)
                ->where('store_delete', '=', 0)
	    		->get();
    	}
    }

    public function ShowBranch($id) {
    	return $branches = Branch::find($id);
    }

    public function InsertBranch($request) {
    	$this->branch_name = $request->branch_name;
    	$this->branch_address = $request->branch_address;
    	$this->branch_delete = 0;
    	$this->store_id = $request->store_id;
    	$this->save();
    }

    public function UpdateBranch($request, $id) {
    	$branch = Branch::find($id);
    	$branch->branch_name = $request->branch_name;
    	$branch->branch_address = $request->branch_address;
    	$branch->store_id = $request->store_id;
    	$branch->save();
    }

    public function DeleteBranch($id) {
    	$branch = Branch::find($id);
    	$branch->branch_delete = 1;
    	$branch->save();
    }
}

app/Http/Controllers/BranchController.php
<?php

namespace App\Http\Controllers;

use App\Branch;
use App\Store;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Response;
use Auth;

class BranchController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(Auth::user()->user_role == "Super Admin" || Auth::user()->user_role == "Owner") {
            $branch = new Branch();
            $branches = [];

            $store = new Store();
            $stores = [];
            if(Auth::user()->user_role == "Super Admin") {
                $branches = $branch->SelectBranch();
                $stores = $store->SelectStore();
            } else {
                $branches = $branch->SelectBranch(Auth::user()->store_id);
                $stores = $store->ShowStore(Auth::user()->store_id);
            }

            return view('branch.index', compact('branches', 'stores'));
        } else {
            return redirect()->back();
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * branch a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $branch = new Branch();
        $insert = $branch->InsertBranch($request);
        $branches = $branch->SelectBranch();

        $data['success'] = true;
        $data['data'] = $branches->toArray();

        return Response::json($data);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\branch  $branch
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $branch = new Branch();
        $branches = $branch->ShowBranch($id);

        $data['success'] = true;
        $data['data'] = $branches->toArray();

        return Response::json($data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\branch  $branch
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\branch  $branch
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $branch = new Branch();
        $update = $branch->UpdateBranch($request, $id);
        $branches = $branch->SelectBranch();

        $data['success'] = true;
        $data['data'] = $branches->toArray();

        return Response::json($data);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\branch  $branch
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $branch = new Branch();
        $delete = $branch->DeleteBranch($id);
        $branches = $branch->SelectBranch();

        $data['success'] = true;
        $data['data'] = $branches->toArray();

        return Response::json($data);
    }

    /**
     * unit a newly created resource in storage.
     *
     * @param  \App\unit  $unit
     * @return \Illuminate\Http\Response
     */
    public function get_branch($id)
    {
        $branch = new Branch();
        $branches = $branch->SelectBranch($id);

        $data['success'] = true;
        $data['data'] = $branches->toArray();

        return Response::json($data);
    }
}

resources/views/branch/index.blade.php
@extends('layouts.master')

@section('title','Cabang')

@section('heading','Cabang')

@section('content')
  @if(Session::has('error'))
    <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('error') }}</p>
  @endif

  @if($message = Session::get('success'))
    <div class="alert alert-success alert-block">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <strong>{{ $message }}</strong>
    </div>
  @endif

  <div class="row">
    <div class="col-lg-8">
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <div class="row">
            <div class="col-lg-6 col-xs-6 col-md-6">
              <h6 class="m-0 font-weight-bold text-primary">Daftar Cabang
                @if(Auth::user()->user_role == "Owner")
                  - {{ $stores->store_name }}
                @endif
              </h6>
            </div>
            @if(Auth::user()->user_role == "Super Admin")
              <div class="col-lg-6 col-xs-6 col-md-6">
                <select class="form-control" id="filter_brand">
                  <option value="">-- Pilih Brand --</option>
                  @foreach($stores as $row)
                    <option value="{{ $row->store_name }}">{{ $row->store_name }}</option>
                  @endforeach
                </select>
              </div>
            @endif
          </div>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th>No</th>
                  <th>Nama</th>
                  <th>Alamat</th>
                  @if(Auth::user()->user_role == "Super Admin")
                    <th>Brand</th>
                  @endif
                  <th>Aksi</th>
                </tr>
              </thead>
              <tbody id="table_data">
                @foreach($branches as $row)
                  <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $row->branch_name }}</td>
                    <td>{{ $row->branch_address }}</td>
                    @if(Auth::user()->user_role == "Super Admin")
                      <td>{{ $row->store_name }}</td>
                    @endif
                    <td>
                      <a class="btn btn-primary edit" data-id="{{ $row->branch_id }}" href="javascript:void(0)">{{ __('Ubah') }}</a>
                      <a class="btn btn-danger delete" data-id="{{ $row->branch_id }}" href="javascript:void(0)">{{ __('Hapus') }}</a>
                    </td>
                  </tr>
                @endforeach
              </tbody>
              <tfoot>
                <tr>
                  <th>No</th>
                  <th>Nama</th>
                  <th>Alamat</th>
                  @if(Auth::user()->user_role == "Super Admin")
                    <th>Brand</th>
                  @endif
                  <th>Aksi</th>
                </tr>
              </tfoot>
            </table>
          </div>
        </div>
      </div>
    </div>

    <div class="col-lg-4">
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary" style="width: 100%;">
            <span id="header_action">Tambah</span> Cabang
            @if(Auth::user()->user_role == "Owner")
              - {{ $stores->store_name }}
            @endif
            <button id="button_add" class="btn btn-primary pull-right"><i class="fa fa-plus"></i> Tambah</button>
            <div class="spinner-border text-primary pull-right" id="loading" hidden="hidden"></div>
          </h6>
        </div>
        <div class="card-body">
          @if(Auth::user()->user_role == "Owner")
            <div class="form-group row">
              <label class="col-sm-12 col-form-label" style="text-align: center;">
                @if(count($branches) == $stores->store_branch_max)
                  <span style="color: red;">Jumlah cabang yang Anda miliki telah mencapai jumlah maksimal. Silahkan hubungi SK Technology untuk menambah kuota cabang yang Anda miliki.</span>
                @else
                  <span style="color: blue;">Maksimal cabang yang bisa Anda tambahkan adalah {{ $stores->store_branch_max }} cabang.</span>
                @endif
              </label>
            </div>
          @endif
          <div class="form-group row">
            <label for="branch_name" class="col-sm-3 col-form-label text-md-right">
              {{ __('Nama') }} <abbr style="color: red;">*</abbr>
            </label>
            <div class="col-sm-7">
              <input type="text" class="form-control" id="branch_name" name="branch_name" value="">
              <p style="color: red;" id="branch_name_feedback">
                <strong>Nama cabang wajib diisi!</strong>
              </p>
            </div>
          </div>
          <div class="form-group row">
            <label for="branch_address" class="col-sm-3 col-form-label text-md-right">
              {{ __('Alamat') }} <abbr style="color: red;">*</abbr>
            </label>
            <div class="col-sm-7">
              <input type="text" class="form-control" id="branch_address" name="branch_address" value="">
              <p style="color: red;" id="branch_address_feedback">
                <strong>Alamat cabang wajib diisi!</strong>
              </p>
            </div>
          </div>
          @if(Auth::user()->user_role == "Super Admin")
            <div class="form-group row">
              <label for="store_id" class="col-sm-3 col-form-label text-md-right">
                {{ __('Brand') }} <abbr style="color: red;">*</abbr>
              </label>
              <div class="col-sm-7">
                <select class="form-control" id="store_id" name="store_id">
                  <option value="">---- Pilih Brand ----</option>
                  @foreach($stores as $row)
                    <option value="{{ $row->store_id }}">{{ $row->store_name }}</option>
                  @endforeach
                </select>
                <p style="color: red;" id="store_id_feedback">
                  <strong>Brand wajib dipilih!</strong>
                </p>
              </div>
            </div>
          @elseif(Auth::user()->user_role == "Owner")
            <input type="text" id="store_id" value="{{ Auth::user()->store_id }}" hidden>
          @endif
          <div class="form-group">
            {{ csrf_field() }}
            <input type="text" id="branch_id" value="" hidden>
            <input type="text" id="type" value="create" hidden>
            <center>
              <button type="button" class="btn btn-primary" id="submit">Simpan</button>
            </center>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="modal_delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Hapus Data</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>  
        <div class="modal-body">
          Apakah anda ingin menghapus data cabang ini?
        </div>
        <div class="modal-footer">
          <button id="button_delete" class="btn btn-secondary">{{ __('Ya, Hapus') }}</button>
          <button class="btn btn-danger" type="button" data-dismiss="modal">Batal</button>
        </div>
      </div>
    </div>
  </div>
@endsection

@section('script')
   <script type="text/javascript">
    $('#branch_name_feedback').attr('hidden', 'hidden');
    $('#branch_address_feedback').attr('hidden', 'hidden');
    $('#store_id_feedback').attr('hidden', 'hidden');

    $('#button_add').attr('hidden', 'hidden');
    
    var table = $('#dataTable').DataTable();
    $('#filter_brand').change(function() {
      table.column(3).search($('#filter_brand').val());
      table.draw();
    });

    $('#submit').click(function() {
      $('#branch_name_feedback').attr('hidden', 'hidden');
      $('#branch_address_feedback').attr('hidden', 'hidden');
      $('#store_id_feedback').attr('hidden', 'hidden');

      var type = $('#type').val();
      if(type == "create") {
        var branch_name = $('#branch_name').val();
        var branch_address = $('#branch_address').val();
        var store_id = $('#store_id').val();
        var _token = $('input[name=_token]').val();
        
        if(branch_name == "") {
          $('#branch_name_feedback').removeAttr('hidden');
        } else if(branch_address == "") {
          $('#branch_address_feedback').removeAttr('hidden');
        } else if(store_id == "") {
          $('#store_id_feedback').removeAttr('hidden');
        } else {
          $('#loading').removeAttr('hidden');
          $.ajax({
            url: "{{ route('cabang.store') }}",
            method: "POST",  
            data: {
              branch_name : branch_name, 
              branch_address : branch_address, 
              store_id : store_id, 
              _token : _token
            },
            success: function(result) {
              location.reload();
            }
          });
        }
      } else if(type == "edit") {
        var branch_id = $('#branch_id').val();
        var branch_name = $('#branch_name').val();
        var branch_address = $('#branch_address').val();
        var store_id = $('#store_id').val();
        var _token = $('input[name=_token]').val();

        var url = "{{ route('cabang.update', 'branch_id') }}";
        url = url.replace('branch_id', branch_id);

        if(branch_name == "") {
          $('#branch_name_feedback').removeAttr('hidden');
        } else if(branch_address == "") {
          $('#branch_address_feedback').removeAttr('hidden');
        } else if(store_id == "") {
          $('#store_id_feedback').removeAttr('hidden');
        } else {
          $('#loading').removeAttr('hidden');
          $.ajax({
            url: url,
            method: "PUT",  
            data: {
              branch_id : branch_id, 
              branch_name : branch_name, 
              branch_address : branch_address, 
              store_id : store_id, 
              _token : _token
            },
            success: function(result) {
              location.reload();
            }
          });
        }
      }
    });

    $(document).delegate('.edit', 'click', function() {
      $('#header_action').html('Ubah');
      $('#type').val('edit');
      $('#button_add').removeAttr('hidden');

      var branch_id = $(this).data('id');
      var _token = $('input[name=_token]').val();

      var url = "{{ route('cabang.show', 'branch_id') }}";
      url = url.replace('branch_id', branch_id);

      $.ajax({
        url: url,
        method: "GET",  
        data: {
          branch_id : branch_id, 
          _token : _token
        },
        success: function(result) {
          $('#branch_id').val(branch_id);
          $('#branch_name').val(result.data.branch_name);
          $('#branch_address').val(result.data.branch_address);
          $('#store_id').val(result.data.store_id);
        }
      });
    });

    var branch_id = "";
    $(document).delegate('.delete', 'click', function() {
      branch_id = $(this).data('id');

      $('#modal_delete').modal("show");
      $('#button_delete').click(function() {
        var _token = $('input[name=_token]').val();
        
        var url = "{{ route('cabang.destroy', 'branch_id') }}";
        url = url.replace('branch_id', branch_id);

        $.ajax({
          url: url,
          method: "DELETE",  
          data: {
            branch_id : branch_id, 
            _token : _token
          },
          success: function(result) {
            location.reload();
          }
        });
      });
    });

    $('#button_add').click(function() {
      $('#header_action').html('Tambah');
      $('#type').val('create');
      $('#button_add').attr('hidden', 'hidden');

      $('#branch_id').val('');
      $('#branch_name').val('');
      $('#branch_address').val('');
      $('#store_id').val('');
      if("{{ Auth::user()->user_role }}" != "Super Admin") {
        $('#store_id').val("{{ Auth::user()->store_id }}")
      }
    });

    $('#button_add').click();
    if("{{ Auth::user()->user_role }}" != "Super Admin") {
      $('#store_id').val("{{ Auth::user()->store_id }}")
    }
  </script>
@endsection