routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('admin', 'AdminController');
Route::resource('atur_akun', 'AccountSettingController');
Route::resource('akun', 'AccountController');
Route::resource('bahan_baku', 'IngredientController');
Route::resource('bahan_baku_menu', 'MenuIngredientController');
Route::resource('biaya_lain', 'OtherTransactionController');
Route::resource('cabang', 'BranchController');
Route::resource('jenis_akun', 'AccountTypeController');
Route::resource('jenis_pembayaran', 'PaymentTypeController');
Route::resource('jurnal', 'JournalController');
Route::resource('kasir', 'CashierController');
Route::resource('kategori', 'CategoryController');
Route::resource('member', 'MemberController');
Route::resource('menu', 'MenuController');
Route::resource('owner', 'OwnerController');
Route::resource('satuan', 'UnitController');
Route::resource('transfer', 'TransferController');
Route::resource('pembelian', 'RestockController');
Route::resource('penjualan', 'TransactionController');
Route::resource('brand', 'StoreController');
Route::resource('jenis_penjualan', 'TransactionTypeController');
Route::resource('konversi_poin', 'SettingPointController');
Route::resource('riwayat_poin', 'HistoryPointController');

Route::get('/get_branch/{store_id}', 'BranchController@get_branch');
Route::get('/get_unit/{branch_id}', 'UnitController@get_unit');
Route::get('/get_category/{branch_id}', 'CategoryController@get_category');
Route::get('/get_ingredient/{branch_id}', 'IngredientController@get_ingredient');
Route::get('/get_account_type/{branch_id}', 'AccountTypeController@get_account_type');
Route::get('/get_account/{branch_id}', 'AccountController@get_account');
Route::get('/get_payment_type/{branch_id}', 'PaymentTypeController@get_payment_type');

Route::get('/laporan/neraca', 'ReportController@neraca_pre')->name('neraca_pre');
Route::get('/laporan/laba_rugi', 'ReportController@laba_rugi_pre')->name('laba_rugi_pre');
Route::get('/laporan/arus_kas', 'ReportController@arus_kas_pre')->name('arus_kas_pre');
Route::get('/laporan/neraca/{store_id}/{branch_id}', 'ReportController@neraca')->name('neraca');
Route::get('/laporan/laba_rugi/{store_id}/{branch_id}', 'ReportController@laba_rugi')->name('laba_rugi');
Route::get('/laporan/arus_kas/{store_id}/{branch_id}', 'ReportController@arus_kas')->name('arus_kas');

Route::get('/invoice_download/penjualan/{transaction_id}', 'PDFController@invoice_transaction');
Route::get('/invoice_download/pembelian/{restock_id}', 'PDFController@invoice_restock');
Route::get('/invoice_download/transfer/{transfer_id}', 'PDFController@invoice_transfer');
Route::get('/invoice_download/biaya_lain/{other_transaction_id}', 'PDFController@invoice_other_transaction');

app/Unit.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use DB;

class Unit extends Model
{
    protected $table = "unit";
    protected $primaryKey = "unit_id";
    public $timestamps = false;

    public function SelectUnit($store_id = 0) {
    	if($store_id == 0) {
	    	return $unites = DB::table('unit')
	    		->join('store', 'store.store_id', '=', 'unit.store_id')
                ->where('store_delete', '=', 0)
	    		->where('unit_delete', '=', 0)
	    		->get();
    	} else {
	    	return $unites = DB::table('unit')
	    		->join('store', 'store.store_id', '=', 'unit.store_id')
	    		->where('store.store_id', '=', $store_id)
	    		->where('unit_delete', '=', 0)
                ->where('store_delete', '=', 0)
	    		->get();
    	}
    }

    public function ShowUnit($id) {
    	return $unites = Unit::find($id);
    }

    public function InsertUnit($request) {
    	$this->unit_name = $request->unit_name;
    	$this->unit_delete = 0;
    	$this->store_id = $request->store_id;
    	$this->save();
    }

    public function UpdateUnit($request, $id) {
    	$unit = Unit::find($id);
    	$unit->unit_name = $request->unit_name;
    	$unit->store_id = $request->store_id;
    	$unit->save();
    }

    public function DeleteUnit($id) {
    	$unit = Unit::find($id);
    	$unit->unit_delete = 1;
    	$unit->save();
    }
}

app/Http/Controllers/UnitController.php
<?php

namespace App\Http\Controllers;

use App\Unit;
use App\Store;
use App\Branch;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Response;
use Auth;

class UnitController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(Auth::user()->user_role == "Super Admin" || Auth::user()->user_role == "Owner") {
            $unit = new Unit();
            $units = [];
            
            $store = new Store();
            $stores = [];
            if(Auth::user()->user_role == "Super Admin") {
                $units = $unit->SelectUnit();
                $stores = $store->SelectStore();
            } else {
                $units = $unit->SelectUnit(Auth::user()->store_id);
                $stores = $store->ShowStore(Auth::user()->store_id);
            }

            return view('unit.index', compact('units', 'stores'));
        } else {
            return redirect()->back();
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * unit a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $unit = new Unit();
        $insert = $unit->InsertUnit($request);
        $units = $unit->SelectUnit();

        $data['success'] = true;
        $data['data'] = $units->toArray();

        return Response::json($data);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\unit  $unit
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $unit = new Unit();
        $units = $unit->ShowUnit($id);

        $data['success'] = true;
        $data['data'] = $units->toArray();

        return Response::json($data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\unit  $unit
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\unit  $unit
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $unit = new Unit();
        $update = $unit->UpdateUnit($request, $id);
        $units = $unit->SelectUnit();

        $data['success'] = true;
        $data['data'] = $units->toArray();

        return Response::json($data);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\unit  $unit
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $unit = new Unit();
        $delete = $unit->DeleteUnit($id);
        $units = $unit->SelectUnit();

        $data['success'] = true;
        $data['data'] = $units->toArray();

        return Response::json($data);
    }

    /**
     * unit a newly created resource in storage.
     *
     * @param  \App\unit  $unit
     * @return \Illuminate\Http\Response
     */
    public function get_unit($id)
    {
        if($id[0] == "s") {
            $unit = new Unit();
            $units = $unit->SelectUnit(substr($id, 1));
        } else {
            $branch = new Branch();
            $branches = $branch->ShowBranch($id);

            $unit = new Unit();
            $units = $unit->SelectUnit($branches->store_id);
        }

        $data['success'] = true;
        $data['data'] = $units->toArray();

        return Response::json($data);
    }
}

resources/views/unit/index.blade.php
@extends('layouts.master')

@section('title','Satuan')

@section('heading','Satuan')

@section('content')
  @if(Session::has('error'))
    <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('error') }}</p>
  @endif

  @if($message = Session::get('success'))
    <div class="alert alert-success alert-block">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <strong>{{ $message }}</strong>
    </div>
  @endif

  <div class="row">
    <div class="col-lg-8">
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <div class="row">
            <div class="col-lg-6 col-xs-6 col-md-6">
              <h6 class="m-0 font-weight-bold text-primary">Daftar Satuan
                @if(Auth::user()->user_role == "Owner")
                  - {{ $stores->store_name }}
                @endif
              </h6>
            </div>
            @if(Auth::user()->user_role == "Super Admin")
              <div class="col-lg-6 col-xs-6 col-md-6">
                <select class="form-control" id="filter_brand">
                  <option value="">-- Pilih Brand --</option>
                  @foreach($stores as $row)
                    <option value="{{ $row->store_name }}">{{ $row->store_name }}</option>
                  @endforeach
                </select>
              </div>
            @endif
          </div>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th>No</th>
                  <th>Nama</th>
                  @if(Auth::user()->user_role == "Super Admin")
                    <th>Brand</th>
                  @endif
                  <th>Aksi</th>
                </tr>
              </thead>
              <tbody id="table_data">
                @foreach($units as $row)
                  <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $row->unit_name }}</td>
                    @if(Auth::user()->user_role == "Super Admin")
                      <td>{{ $row->store_name }}</td>
                    @endif
                    <td>
                      <a class="btn btn-primary edit" data-id="{{ $row->unit_id }}" href="javascript:void(0)">{{ __('Ubah') }}</a>
                      <a class="btn btn-danger delete" data-id="{{ $row->unit_id }}" href="javascript:void(0)">{{ __('Hapus') }}</a>
                    </td>
                  </tr>
                @endforeach
              </tbody>
              <tfoot>
                <tr>
                  <th>No</th>
                  <th>Nama</th>
                  @if(Auth::user()->user_role == "Super Admin")
                    <th>Brand</th>
                  @endif
                  <th>Aksi</th>
                </tr>
              </tfoot>
            </table>
          </div>
        </div>
      </div>
    </div>

    <div class="col-lg-4">
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary" style="width: 100%;">
            <span id="header_action">Tambah</span> Satuan
            @if(Auth::user()->user_role == "Owner")
              - {{ $stores->store_name }}
            @endif
            <button id="button_add" class="btn btn-primary pull-right"><i class="fa fa-plus"></i> Tambah</button>
            <div class="spinner-border text-primary pull-right" id="loading" hidden="hidden"></div>
          </h6>
        </div>
        <div class="card-body">
          <div class="form-group row">
            <label for="unit_name" class="col-sm-3 col-form-label text-md-right">
              {{ __('Nama') }} <abbr style="color: red;">*</abbr>
            </label>
            <div class="col-sm-7">
              <input type="text" class="form-control" id="unit_name" name="unit_name" value="">
              <p style="color: red;" id="unit_name_feedback">
                <strong>Nama satuan wajib diisi!</strong>
              </p>
            </div>
          </div>
          @if(Auth::user()->user_role == "Super Admin")
            <div class="form-group row">
              <label for="store_id" class="col-sm-3 col-form-label text-md-right">
                {{ __('Brand') }} <abbr style="color: red;">*</abbr>
              </label>
              <div class="col-sm-7">
                <select class="form-control" id="store_id" name="store_id">
                  <option value="">---- Pilih Brand ----</option>
                  @foreach($stores as $row)
                    <option value="{{ $row->store_id }}">{{ $row->store_name }}</option>
                  @endforeach
                </select>
                <p style="color: red;" id="store_id_feedback">
                  <strong>Brand wajib dipilih!</strong>
                </p>
              </div>
            </div>
          @elseif(Auth::user()->user_role == "Owner" || Auth::user()->user_role == "Admin")
            <input type="text" id="store_id" value="{{ Auth::user()->store_id }}" hidden>
          @endif
          <div class="form-group">
            {{ csrf_field() }}
            <input type="text" id="unit_id" value="" hidden>
            <input type="text" id="type" value="create" hidden>
            <center>
              <button type="button" class="btn btn-primary" id="submit">Simpan</button>
            </center>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="modal_delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Hapus Data</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>  
        <div class="modal-body">
          Apakah anda ingin menghapus data satuan ini?
        </div>
        <div class="modal-footer">
          <button id="button_delete" class="btn btn-secondary">{{ __('Ya, Hapus') }}</button>
          <button class="btn btn-danger" type="button" data-dismiss="modal">Batal</button>
        </div>
      </div>
    </div>
  </div>
@endsection

@section('script')
   <script type="text/javascript">
    $('#unit_name_feedback').attr('hidden', 'hidden');
    $('#store_id_feedback').attr('hidden', 'hidden');

    $('#button_add').attr('hidden', 'hidden');

    var table = $('#dataTable').DataTable();
    $('#filter_brand').change(function() {
      table.column(2).search($('#filter_brand').val());
      table.draw();
    });

    $('#submit').click(function() {
      $('#unit_name_feedback').attr('hidden', 'hidden');
      $('#store_id_feedback').attr('hidden', 'hidden');

      var type = $('#type').val();
      if(type == "create") {
        var unit_name = $('#unit_name').val();
        var store_id = $('#store_id').val();
        var _token = $('input[name=_token]').val();
        
        if(unit_name == "") {
          $('#unit_name_feedback').removeAttr('hidden');
        } else if(store_id == "") {
          $('#store_id_feedback').removeAttr('hidden');
        } else {
          $('#loading').removeAttr('hidden');
          $.ajax({
            url: "{{ route('satuan.store') }}",
            method: "POST",  
            data: {
              unit_name : unit_name, 
              store_id : store_id, 
              _token : _token
            },
            success: function(result) {
              location.reload();
            }
          });
        }
      } else if(type == "edit") {
        var unit_id = $('#unit_id').val();
        var unit_name = $('#unit_name').val();
        var store_id = $('#store_id').val();
        var _token = $('input[name=_token]').val();

        var url = "{{ route('satuan.update', 'unit_id') }}";
        url = url.replace('unit_id', unit_id);

        if(unit_name == "") {
          $('#unit_name_feedback').removeAttr('hidden');
        } else if(store_id == "") {
          $('#store_id_feedback').removeAttr('hidden');
        } else {
          $('#loading').removeAttr('hidden');
          $.ajax({
            url: url,
            method: "PUT",  
            data: {
              unit_id : unit_id, 
              unit_name : unit_name, 
              store_id : store_id, 
              _token : _token
            },
            success: function(result) {
              location.reload();
            }
          });
        }
      }
    });

    $(document).delegate('.edit', 'click', function() {
      $('#header_action').html('Ubah');
      $('#type').val('edit');
      $('#button_add').removeAttr('hidden');

      var unit_id = $(this).data('id');
      var _token = $('input[name=_token]').val();

      var url = "{{ route('satuan.show', 'unit_id') }}";
      url = url.replace('unit_id', unit_id);

      $.ajax({
        url: url,
        method: "GET",  
        data: {
          unit_id : unit_id, 
          _token : _token
        },
        success: function(result) {
          $('#unit_id').val(unit_id);
          $('#unit_name').val(result.data.unit_name);
          $('#store_id').val(result.data.store_id);
        }
      });
    });

    var unit_id = "";
    $(document).delegate('.delete', 'click', function() {
      unit_id = $(this).data('id');

      $('#modal_delete').modal("show");
      $('#button_delete').click(function() {
        var _token = $('input[name=_token]').val();
        
        var url = "{{ route('satuan.destroy', 'unit_id') }}";
        url = url.replace('unit_id', unit_id);

        $.ajax({
          url: url,
          method: "DELETE",  
          data: {
            unit_id : unit_id, 
            _token : _token
          },
          success: function(result) {
            location.reload();
          }
        });
      });
    });

    $('#button_add').click(function() {
      $('#header_action').html('Tambah');
      $('#type').val('create');
      $('#button_add').attr('hidden', 'hidden');

      $('#unit_id').val('');
      $('#unit_name').val('');
      $('#store_id').val('');
      if("{{ Auth::user()->user_role }}" != "Super Admin") {
        $('#store_id').val("{{ Auth::user()->store_id }}")
      }
    });

    $('#button_add').click();
    if("{{ Auth::user()->user_role }}" != "Super Admin") {
      $('#store_id').val("{{ Auth::user()->store_id }}")
    }
  </script>
@endsection