routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('admin', 'AdminController');
Route::resource('atur_akun', 'AccountSettingController');
Route::resource('akun', 'AccountController');
Route::resource('bahan_baku', 'IngredientController');
Route::resource('bahan_baku_menu', 'MenuIngredientController');
Route::resource('biaya_lain', 'OtherTransactionController');
Route::resource('cabang', 'BranchController');
Route::resource('jenis_akun', 'AccountTypeController');
Route::resource('jenis_pembayaran', 'PaymentTypeController');
Route::resource('jurnal', 'JournalController');
Route::resource('kasir', 'CashierController');
Route::resource('kategori', 'CategoryController');
Route::resource('member', 'MemberController');
Route::resource('menu', 'MenuController');
Route::resource('owner', 'OwnerController');
Route::resource('satuan', 'UnitController');
Route::resource('transfer', 'TransferController');
Route::resource('pembelian', 'RestockController');
Route::resource('penjualan', 'TransactionController');
Route::resource('brand', 'StoreController');
Route::resource('jenis_penjualan', 'TransactionTypeController');
Route::resource('konversi_poin', 'SettingPointController');
Route::resource('riwayat_poin', 'HistoryPointController');

Route::get('/get_branch/{store_id}', 'BranchController@get_branch');
Route::get('/get_unit/{branch_id}', 'UnitController@get_unit');
Route::get('/get_category/{branch_id}', 'CategoryController@get_category');
Route::get('/get_ingredient/{branch_id}', 'IngredientController@get_ingredient');
Route::get('/get_account_type/{branch_id}', 'AccountTypeController@get_account_type');
Route::get('/get_account/{branch_id}', 'AccountController@get_account');
Route::get('/get_payment_type/{branch_id}', 'PaymentTypeController@get_payment_type');

Route::get('/laporan/neraca', 'ReportController@neraca_pre')->name('neraca_pre');
Route::get('/laporan/laba_rugi', 'ReportController@laba_rugi_pre')->name('laba_rugi_pre');
Route::get('/laporan/arus_kas', 'ReportController@arus_kas_pre')->name('arus_kas_pre');
Route::get('/laporan/neraca/{store_id}/{branch_id}', 'ReportController@neraca')->name('neraca');
Route::get('/laporan/laba_rugi/{store_id}/{branch_id}', 'ReportController@laba_rugi')->name('laba_rugi');
Route::get('/laporan/arus_kas/{store_id}/{branch_id}', 'ReportController@arus_kas')->name('arus_kas');

Route::get('/invoice_download/penjualan/{transaction_id}', 'PDFController@invoice_transaction');
Route::get('/invoice_download/pembelian/{restock_id}', 'PDFController@invoice_restock');
Route::get('/invoice_download/transfer/{transfer_id}', 'PDFController@invoice_transfer');
Route::get('/invoice_download/biaya_lain/{other_transaction_id}', 'PDFController@invoice_other_transaction');

app/AccountSetting.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use DB;

class AccountSetting extends Model
{
    protected $table = "account_setting";
    protected $primaryKey = "account_setting_id";
    public $timestamps = false;

    public function SelectAccountSetting($branch_id = 0) {
    	return $account_settings = DB::table('account_setting')
    		->where('branch_id', '=', $branch_id)
    		->get();
    }

    public function InsertAccountSetting($request) {
    	$account_settings = DB::table('account_setting')
    		->where('account_setting_type', '=', $request->account_setting_type)
    		->where('branch_id', '=', $request->branch_id)
    		->delete();

    	$this->account_setting_type = $request->account_setting_type;
    	$this->account_id = $request->account_id;
    	$this->branch_id = $request->branch_id;
    	$this->save();
    }
}

app/Http/Controllers/AccountSettingController.php
<?php

namespace App\Http\Controllers;

use App\Account;
use App\AccountSetting;
use App\Branch;
use App\Store;
use Illuminate\Http\Request;
use Auth;
use Response;

class AccountSettingController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(Auth::user()->user_role == "Super Admin" || Auth::user()->user_role == "Owner") {
            $branch = new Branch();
            $branches = [];

            $store = new Store();
            $stores = [];

            if(Auth::user()->user_role == "Super Admin") {
                $branches = $branch->SelectBranch();
                $stores = $store->SelectStore();

                $branches_temp = [];
                foreach ($branches as $row) {
                    $branches_temp[$row->store_id][] = $row;
                }
                $branches = $branches_temp;
            } else {
                $branches = $branch->SelectBranch(Auth::user()->store_id);
                $stores = $store->ShowStore(Auth::user()->store_id);
            }

            return view('account_setting.pre_index', compact('branches', 'stores'));
        } else if(Auth::user()->user_role == "Admin") {
            return redirect()->back();
        } else {
            return redirect()->back();
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $account_setting = new AccountSetting();
        $insert = $account_setting->InsertAccountSetting($request);
        $account_settings = $account_setting->SelectAccountSetting();

        $data['success'] = true;
        $data['data'] = $account_settings->toArray();

        return Response::json($data);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\AccountSetting  $accountSetting
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if(Auth::user()->user_role == "Super Admin" || Auth::user()->user_role == "Owner") {
            $account_setting = new AccountSetting();
            $account_settings_temp = $account_setting->SelectAccountSetting($id);

            $account_settings = [];
            foreach($account_settings_temp as $row) {
                $account_settings[$row->account_setting_type] = $row;
            }

            $account = new Account();
            $accounts = $account->SelectAccount(0, $id);

            $branch = new Branch();
            $branches = $branch->ShowBranch($id);

            $store = new Store();
            $stores = $store->ShowStore($branches->store_id);

            return view('account_setting.index', compact('account_settings', 'accounts', 'branches', 'stores'));
        } else {
            return redirect()->back();
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\AccountSetting  $accountSetting
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\AccountSetting  $accountSetting
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\AccountSetting  $accountSetting
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/account_setting/index.blade.php
@extends('layouts.master')

@section('title','Setting Akun')

@section('heading','Setting Akun')

@section('content')
  @if(Session::has('error'))
    <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('error') }}</p>
  @endif

  @if($message = Session::get('success'))
    <div class="alert alert-success alert-block">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <strong>{{ $message }}</strong>
    </div>
  @endif

  <div class="row">
    <div class="col-lg-12">
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <div class="row">
            <div class="col-lg-6 col-xs-6 col-md-6">
              <h6 class="m-0 font-weight-bold text-primary">Setting Akun - 
                @if(Auth::user()->user_role == "Super Admin")
                  {{ $stores->store_name }}
                @endif
                {{ $branches->branch_name }}
              </h6>
            </div>
            <div class="spinner-border text-primary pull-right" id="loading" hidden="hidden"></div>
          </div>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <input type="hidden" id="branch_id" value="{{ $branches->branch_id }}">
            <table class="table table-bordered" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th>Tipe</th>
                  <th>Akun</th>
                  <th>Aksi</th>
                </tr>
              </thead>
              <tbody id="table_data">
                <tr>
                  <td>Debet Potongan Penjualan</td>
                  <td>
                    <input type="hidden" id="account-setting-type-debet-potongan-penjualan" value="Debet Potongan Penjualan">
                    <select id="account-id-debet-potongan-penjualan" class="form-control">
                      <option value="">-- Pilih Akun --</option>
                      @foreach($accounts as $row)
                        @if(isset($account_settings['Debet Potongan Penjualan']))
                          @if($account_settings['Debet Potongan Penjualan']->account_id == $row->account_id)
                            <option value="{{ $row->account_id }}" selected>{{ $row->account_name }} {{ $row->payment_type_name }}</option>
                          @else
                            <option value="{{ $row->account_id }}">{{ $row->account_name }} {{ $row->payment_type_name }}</option>
                          @endif
                        @else
                          <option value="{{ $row->account_id }}">{{ $row->account_name }} {{ $row->payment_type_name }}</option>
                        @endif
                      @endforeach
                    </select>
                    <p style="color: red;" id="account_id_debet_potongan_penjualan_feedback">
                      <strong>Akun wajib dipilih!</strong>
                    </p>
                  </td>
                  <td>
                    <button class="btn btn-success btn-save" data-account-id="account-id-debet-potongan-penjualan" data-account-setting-type="account-setting-type-debet-potongan-penjualan" data-feedback="account_id_debet_potongan_penjualan_feedback">Simpan</button>
                  </td>
                </tr>
                <tr>
                  <td>Debet Diskon Penjualan</td>
                  <td>
                    <input type="hidden" id="account-setting-type-debet-diskon-penjualan" value="Debet Diskon Penjualan">
                    <select id="account-id-debet-diskon-penjualan" class="form-control">
                      <option value="">-- Pilih Akun --</option>
                      @foreach($accounts as $row)
                        @if(isset($account_settings['Debet Diskon Penjualan']))
                          @if($account_settings['Debet Diskon Penjualan']->account_id == $row->account_id)
                            <option value="{{ $row->account_id }}" selected>{{ $row->account_name }} {{ $row->payment_type_name }}</option>
                          @else
                            <option value="{{ $row->account_id }}">{{ $row->account_name }} {{ $row->payment_type_name }}</option>
                          @endif
                        @else
                          <option value="{{ $row->account_id }}">{{ $row->account_name }} {{ $row->payment_type_name }}</option>
                        @endif
                      @endforeach
                    </select>
                    <p style="color: red;" id="account_id_debet_diskon_penjualan_feedback">
                      <strong>Akun wajib dipilih!</strong>
                    </p>
                  </td>
                  <td>
                    <button class="btn btn-success btn-save" data-account-id="account-id-debet-diskon-penjualan" data-account-setting-type="account-setting-type-debet-diskon-penjualan" data-feedback="account_id_debet_diskon_penjualan_feedback">Simpan</button>
                  </td>
                </tr>
                <tr>
                  <td>Kredit Nota Penjualan</td>
                  <td>
                    <input type="hidden" id="account-setting-type-kredit-nota-penjualan" value="Kredit Nota Penjualan">
                    <select id="account-id-kredit-nota-penjualan" class="form-control">
                      <option value="">-- Pilih Akun --</option>
                      @foreach($accounts as $row)
                        @if(isset($account_settings['Kredit Nota Penjualan']))
                          @if($account_settings['Kredit Nota Penjualan']->account_id == $row->account_id)
                            <option value="{{ $row->account_id }}" selected>{{ $row->account_name }} {{ $row->payment_type_name }}</option>
                          @else
                            <option value="{{ $row->account_id }}">{{ $row->account_name }} {{ $row->payment_type_name }}</option>
                          @endif
                        @else
                          <option value="{{ $row->account_id }}">{{ $row->account_name }} {{ $row->payment_type_name }}</option>
                        @endif
                      @endforeach
                    </select>
                    <p style="color: red;" id="account_id_kredit_nota_penjualan_feedback">
                      <strong>Akun wajib dipilih!</strong>
                    </p>
                  </td>
                  <td>
                    <button class="btn btn-success btn-save" data-account-id="account-id-kredit-nota-penjualan" data-account-setting-type="account-setting-type-kredit-nota-penjualan" data-feedback="account_id_kredit_nota_penjualan_feedback">Simpan</button>
                  </td>
                </tr>
                <tr>
                  <td>Debet Bahan Baku Penjualan</td>
                  <td>
                    <input type="hidden" id="account-setting-type-debet-bahan-baku-penjualan" value="Debet Bahan Baku Penjualan">
                    <select id="account-id-debet-bahan-baku-penjualan" class="form-control">
                      <option value="">-- Pilih Akun --</option>
                      @foreach($accounts as $row)
                        @if(isset($account_settings['Debet Bahan Baku Penjualan']))
                          @if($account_settings['Debet Bahan Baku Penjualan']->account_id == $row->account_id)
                            <option value="{{ $row->account_id }}" selected>{{ $row->account_name }} {{ $row->payment_type_name }}</option>
                          @else
                            <option value="{{ $row->account_id }}">{{ $row->account_name }} {{ $row->payment_type_name }}</option>
                          @endif
                        @else
                          <option value="{{ $row->account_id }}">{{ $row->account_name }} {{ $row->payment_type_name }}</option>
                        @endif
                      @endforeach
                    </select>
                    <p style="color: red;" id="account_id_debet_bahan_baku_penjualan_feedback">
                      <strong>Akun wajib dipilih!</strong>
                    </p>
                  </td>
                  <td>
                    <button class="btn btn-success btn-save" data-account-id="account-id-debet-bahan-baku-penjualan" data-account-setting-type="account-setting-type-debet-bahan-baku-penjualan" data-feedback="account_id_debet_bahan_baku_penjualan_feedback">Simpan</button>
                  </td>
                </tr>
                <tr>
                  <td>Kredit Bahan Baku Penjualan</td>
                  <td>
                    <input type="hidden" id="account-setting-type-kredit-bahan-baku-penjualan" value="Kredit Bahan Baku Penjualan">
                    <select id="account-id-kredit-bahan-baku-penjualan" class="form-control">
                      <option value="">-- Pilih Akun --</option>
                      @foreach($accounts as $row)
                        @if(isset($account_settings['Kredit Bahan Baku Penjualan']))
                          @if($account_settings['Kredit Bahan Baku Penjualan']->account_id == $row->account_id)
                            <option value="{{ $row->account_id }}" selected>{{ $row->account_name }} {{ $row->payment_type_name }}</option>
                          @else
                            <option value="{{ $row->account_id }}">{{ $row->account_name }} {{ $row->payment_type_name }}</option>
                          @endif
                        @else
                          <option value="{{ $row->account_id }}">{{ $row->account_name }} {{ $row->payment_type_name }}</option>
                        @endif
                      @endforeach
                    </select>
                    <p style="color: red;" id="account_id_kredit_bahan_baku_penjualan_feedback">
                      <strong>Akun wajib dipilih!</strong>
                    </p>
                  </td>
                  <td>
                    <button class="btn btn-success btn-save" data-account-id="account-id-kredit-bahan-baku-penjualan" data-account-setting-type="account-setting-type-kredit-bahan-baku-penjualan" data-feedback="account_id_kredit_bahan_baku_penjualan_feedback">Simpan</button>
                  </td>
                </tr>
                <tr>
                  <td>Debet Kredit Hutang Dagang</td>
                  <td>
                    <input type="hidden" id="account-setting-type-debet-kredit-hutang-dagang" value="Debet Kredit Hutang Dagang">
                    <select id="account-id-debet-kredit-hutang-dagang" class="form-control">
                      <option value="">-- Pilih Akun --</option>
                      @foreach($accounts as $row)
                        @if(isset($account_settings['Debet Kredit Hutang Dagang']))
                          @if($account_settings['Debet Kredit Hutang Dagang']->account_id == $row->account_id)
                            <option value="{{ $row->account_id }}" selected>{{ $row->account_name }} {{ $row->payment_type_name }}</option>
                          @else
                            <option value="{{ $row->account_id }}">{{ $row->account_name }} {{ $row->payment_type_name }}</option>
                          @endif
                        @else
                          <option value="{{ $row->account_id }}">{{ $row->account_name }} {{ $row->payment_type_name }}</option>
                        @endif
                      @endforeach
                    </select>
                    <p style="color: red;" id="account_id_debet_kredit_hutang_dagang_feedback">
                      <strong>Akun wajib dipilih!</strong>
                    </p>
                  </td>
                  <td>
                    <button class="btn btn-success btn-save" data-account-id="account-id-debet-kredit-hutang-dagang" data-account-setting-type="account-setting-type-debet-kredit-hutang-dagang" data-feedback="account_id_debet_kredit_hutang_dagang_feedback">Simpan</button>
                  </td>
                </tr>
              </tbody>
              <tfoot>
                <tr>
                  <th>Tipe</th>
                  <th>Akun</th>
                  <th>Aksi</th>
                </tr>
              </tfoot>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

  {{ csrf_field() }}
@endsection

@section('script')
  <script type="text/javascript">
    $('#account_id_debet_potongan_penjualan_feedback').attr('hidden', 'hidden');
    $('#account_id_debet_diskon_penjualan_feedback').attr('hidden', 'hidden');
    $('#account_id_kredit_nota_penjualan_feedback').attr('hidden', 'hidden');
    $('#account_id_debet_bahan_baku_penjualan_feedback').attr('hidden', 'hidden');
    $('#account_id_kredit_bahan_baku_penjualan_feedback').attr('hidden', 'hidden');
    $('#account_id_debet_kredit_hutang_dagang_feedback').attr('hidden', 'hidden');

    $('.btn-save').click(function() {
      var field_account_id = $(this).data('account-id');
      var field_account_setting_type = $(this).data('account-setting-type');
      var feedback = $(this).data('feedback');

      var account_id = $('#' + field_account_id).val();
      var account_setting_type = $('#' + field_account_setting_type).val();
      var branch_id = $('#branch_id').val();
      var _token = $('input[name=_token]').val();
      
      if(account_id == "") {
        $('#' + feedback).removeAttr('hidden');
      } else {
        $('#loading').removeAttr('hidden');
        $.ajax({
          url: "{{ route('atur_akun.store') }}",
          method: "POST",  
          data: {
            account_id : account_id,
            account_setting_type : account_setting_type,
            branch_id : branch_id, 
            _token : _token
          },
          success: function(result) {
            location.reload();
          }
        });
      }
    });
  </script>
@endsection

resources/views/account_setting/pre_index.blade.php
@extends('layouts.master')

@section('title','Setting Akun')

@section('heading','Setting Akun')

@section('content')
  @if(Session::has('error'))
    <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('error') }}</p>
  @endif

  @if($message = Session::get('success'))
    <div class="alert alert-success alert-block">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <strong>{{ $message }}</strong>
    </div>
  @endif

  <div class="row">
    <div class="col-lg-12">
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <div class="row">
            <div class="col-lg-6 col-xs-6 col-md-6">
              <h6 class="m-0 font-weight-bold text-primary">Pilih Cabang
              </h6>
            </div>
          </div>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th>Nama</th>
                  <th>Aksi</th>
                </tr>
              </thead>
              <tbody id="table_data">
                @if(Auth::user()->user_role == "Super Admin")
                  @foreach($stores as $row)
                    <tr>
                      <td>{{ $row->store_name }}</td>
                      <td>
                        @if(isset($branches[$row->store_id]))
                          @foreach($branches[$row->store_id] as $row_branch)
                            <a class="btn btn-primary" href="{{ url('/atur_akun/' . $row_branch->branch_id) }}">{{ $row_branch->branch_name }}</a>
                          @endforeach
                        @endif
                      </td>
                    </tr>
                  @endforeach
                @elseif(Auth::user()->user_role == "Owner")
                  @foreach($branches as $row)
                    <tr>
                      <td>{{ $row->branch_name }}</td>
                      <td>
                        <a class="btn btn-primary" href="{{ url('/atur_akun/' . $row->branch_id) }}">{{ __('Lihat Setting Akun') }}</a>
                      </td>
                    </tr>
                  @endforeach
                @endif
              </tbody>
              <tfoot>
                <tr>
                  <th>Nama</th>
                  <th>Aksi</th>
                </tr>
              </tfoot>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

@section('script')
  <script type="text/javascript">
    
  </script>
@endsection